## Preprocessing

In [14]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf

# Import pandas and read the charity_data.csv from the provided cloud URL.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [15]:
# Drop the non-beneficial ID columns, 'EIN' 
application_df = application_df.drop(["EIN"],axis=1)

application_df.head()

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [16]:
# Determine the number of unique values in each column.
application_df.nunique()

NAME                      19568
APPLICATION_TYPE             17
AFFILIATION                   6
CLASSIFICATION               71
USE_CASE                      5
ORGANIZATION                  4
STATUS                        2
INCOME_AMT                    9
SPECIAL_CONSIDERATIONS        2
ASK_AMT                    8747
IS_SUCCESSFUL                 2
dtype: int64

In [17]:
# Look at NAME value counts for grouping
name_value_counts = application_df["NAME"].value_counts()

# Check name_value_counts greater than five. 
name_value_counts[name_value_counts>5]

NAME
PARENT BOOSTER USA INC                             1260
TOPS CLUB INC                                       765
UNITED STATES BOWLING CONGRESS INC                  700
WASHINGTON STATE UNIVERSITY                         492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC     408
                                                   ...
OLD OAK CLIFF CONSERVATION LEAGUE INC                 6
AMERICAN NEPHROLOGY NURSES ASSOCIATION                6
HUMBLE ISD EDUCATIONAL SUPPORT GROUPS INC             6
PROFESSIONAL LOADMASTER ASSOCIATION                   6
CBMC INC                                              6
Name: count, Length: 354, dtype: int64

In [18]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
name_groups_to_replace = list(name_value_counts[name_value_counts<=5].index)

# Replace in dataframe
for app in name_groups_to_replace:
    application_df["NAME"] = application_df["NAME"].replace(app,"Other")

# Check to make sure replacement was successful
application_df["NAME"].value_counts()

NAME
Other                                           20043
PARENT BOOSTER USA INC                           1260
TOPS CLUB INC                                     765
UNITED STATES BOWLING CONGRESS INC                700
WASHINGTON STATE UNIVERSITY                       492
                                                ...
HABITAT FOR HUMANITY INTERNATIONAL                  6
DAMAGE PREVENTION COUNCIL OF TEXAS                  6
FLEET RESERVE ASSOCIATION                           6
HUGH OBRIAN YOUTH LEADERSHIP                        6
INTERNATIONAL CONGRESS OF CHURCHES MINISTERS        6
Name: count, Length: 355, dtype: int64

In [19]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_value_counts = application_df["APPLICATION_TYPE"].value_counts()
application_value_counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [20]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(application_value_counts[application_value_counts < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [21]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_value_counts = application_df["CLASSIFICATION"].value_counts()
classification_value_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [22]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification_value_counts[classification_value_counts < 100].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: count, dtype: int64

In [23]:
# Convert categorical data to numeric with `pd.get_dummies`
numeric_df = pd.get_dummies(application_df)
numeric_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_AACE INTERNATIONAL,NAME_ACE MENTOR PROGRAM OF AMERICA INC,NAME_AFRICAN-AMERICAN POSTAL LEAGUE UNITED FOR SUCCESS A-PLUS,NAME_AIR FORCE ASSOCIATION,NAME_ALABAMA FEDERATION OF WOMENS CLUBS,NAME_ALABAMA TREASURE FOREST ASSOCIATION,NAME_ALBANY STATE UNIVERSITY NATIONAL ALUMNI ASSOCIATION,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [24]:
# Convert to a consistent numeric type
numeric_df = numeric_df.astype('float')

In [25]:
# Confirm all columns are numeric
print(numeric_df.dtypes)

STATUS                                    float64
ASK_AMT                                   float64
IS_SUCCESSFUL                             float64
NAME_AACE INTERNATIONAL                   float64
NAME_ACE MENTOR PROGRAM OF AMERICA INC    float64
                                           ...
INCOME_AMT_25000-99999                    float64
INCOME_AMT_50M+                           float64
INCOME_AMT_5M-10M                         float64
SPECIAL_CONSIDERATIONS_N                  float64
SPECIAL_CONSIDERATIONS_Y                  float64
Length: 405, dtype: object

In [26]:
# Split our preprocessed data into our features and target arrays
X = numeric_df.drop(["IS_SUCCESSFUL"], axis=1)
y = numeric_df["IS_SUCCESSFUL"]

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=48)

In [27]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [28]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 50
hidden_nodes_layer2 = 18
hidden_nodes_layer3 = 22

optimized_nn_model = tf.keras.models.Sequential()

# First hidden layer
optimized_nn_model.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Second hidden layer
optimized_nn_model.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Third hidden layer
optimized_nn_model.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="relu"))

# Output layer
optimized_nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
optimized_nn_model.summary()

/opt/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 50)             │        20,250 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 18)             │           918 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 22)             │           418 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            23 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 21,609 (84.41 KB)

 Trainable params: 21,609 (84.41 KB)

 Non-trainable params: 0 (0.00 B)

In [29]:
# Compile the model
optimized_nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [31]:
# Train the model
fit_model = optimized_nn_model.fit(X_train_scaled, y_train, validation_split=0.15, epochs=100)

Epoch 1/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 1s 489us/step - accuracy: 0.7411 - loss: 0.5363 - val_accuracy: 0.7906 - val_loss: 0.4418
Epoch 2/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 411us/step - accuracy: 0.7940 - loss: 0.4313 - val_accuracy: 0.7852 - val_loss: 0.4382
Epoch 3/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 410us/step - accuracy: 0.7938 - loss: 0.4302 - val_accuracy: 0.7917 - val_loss: 0.4379
Epoch 4/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 410us/step - accuracy: 0.7952 - loss: 0.4264 - val_accuracy: 0.7935 - val_loss: 0.4365
Epoch 5/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 410us/step - accuracy: 0.8016 - loss: 0.4174 - val_accuracy: 0.7945 - val_loss: 0.4321
Epoch 6/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 441us/step - accuracy: 0.7983 - loss: 0.4192 - val_accuracy: 0.7911 - val_loss: 0.4323
Epoch 7/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 423us/step - accuracy: 0.7987 - loss: 0.4227 - val_accuracy: 0.7950 - val_loss: 0.4330
Epoch 8/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 447us/step - accuracy: 0.7937 - loss: 0.4244 - val_accuracy: 0.7935 - val_loss: 0.4347
Epoch 9/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 419us/step - accuracy: 0.7997 - loss: 0.4161 - val_accuracy: 0.7919 - val_loss: 0.4365
Epoch 10/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 410us/step - accuracy: 0.8006 - loss: 0.4147 - val_accuracy: 0.7937 - val_loss: 0.4397
Epoch 11/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 409us/step - accuracy: 0.8000 - loss: 0.4165 - val_accuracy: 0.7942 - val_loss: 0.4359
Epoch 12/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 408us/step - accuracy: 0.7988 - loss: 0.4166 - val_accuracy: 0.7937 - val_loss: 0.4358
Epoch 13/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 407us/step - accuracy: 0.7992 - loss: 0.4177 - val_accuracy: 0.7935 - val_loss: 0.4368
Epoch 14/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 408us/step - accuracy: 0.8051 - loss: 0.4097 - val_accuracy: 0.7945 - val_loss: 0.4375
Epoch 15/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 409us/step - accuracy: 0.8049 - loss: 0.4126 - val_accuracy: 0.7922 - val_loss: 0.4375
Epoch 16/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 410us/step - accuracy: 0.8034 - loss: 0.4124 - val_accuracy: 0.7953 - val_loss: 0.4378
Epoch 17/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 410us/step - accuracy: 0.8064 - loss: 0.4074 - val_accuracy: 0.7909 - val_loss: 0.4379
Epoch 18/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 410us/step - accuracy: 0.8055 - loss: 0.4058 - val_accuracy: 0.7919 - val_loss: 0.4396
Epoch 19/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 411us/step - accuracy: 0.8052 - loss: 0.4055 - val_accuracy: 0.7922 - val_loss: 0.4388
Epoch 20/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 410us/step - accuracy: 0.8020 - loss: 0.4146 - val_accuracy: 0.7942 - val_loss: 0.4426
Epoch 21/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 450us/step - accuracy: 0.8080 - loss: 0.4076 - val_accuracy: 0.7930 - val_loss: 0.4424
Epoch 22/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 416us/step - accuracy: 0.8000 - loss: 0.4167 - val_accuracy: 0.7911 - val_loss: 0.4417
Epoch 23/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - accuracy: 0.8050 - loss: 0.4087 - val_accuracy: 0.7945 - val_loss: 0.4381
Epoch 24/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 411us/step - accuracy: 0.8076 - loss: 0.4058 - val_accuracy: 0.7935 - val_loss: 0.4436
Epoch 25/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 413us/step - accuracy: 0.8044 - loss: 0.4080 - val_accuracy: 0.7917 - val_loss: 0.4448
Epoch 26/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - accuracy: 0.8063 - loss: 0.4079 - val_accuracy: 0.7932 - val_loss: 0.4468
Epoch 27/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 411us/step - accuracy: 0.8078 - loss: 0.4068 - val_accuracy: 0.7937 - val_loss: 0.4436
Epoch 28/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 414us/step - accuracy: 0.8036 - loss: 0.4116 - val_accuracy: 0.7955 - val_loss: 0.4493
Epoch 29/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 410us/step - accuracy: 0.8041 - loss: 0.4123 - val_accuracy: 0.7917 - val_loss: 0.4425
Epoch 30/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 414us/step - accuracy: 0.8030 - loss: 0.4131 - val_accuracy: 0.7948 - val_loss: 0.4486
Epoch 31/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - accuracy: 0.8041 - loss: 0.4117 - val_accuracy: 0.7932 - val_loss: 0.4460
Epoch 32/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 416us/step - accuracy: 0.8053 - loss: 0.4061 - val_accuracy: 0.7927 - val_loss: 0.4497
Epoch 33/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 466us/step - accuracy: 0.8016 - loss: 0.4104 - val_accuracy: 0.7932 - val_loss: 0.4478
Epoch 34/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 418us/step - accuracy: 0.8103 - loss: 0.4005 - val_accuracy: 0.7917 - val_loss: 0.4483
Epoch 35/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 415us/step - accuracy: 0.8106 - loss: 0.4000 - val_accuracy: 0.7911 - val_loss: 0.4480
Epoch 36/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 416us/step - accuracy: 0.8077 - loss: 0.4035 - val_accuracy: 0.7922 - val_loss: 0.4488
Epoch 37/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 471us/step - accuracy: 0.8063 - loss: 0.4083 - val_accuracy: 0.7932 - val_loss: 0.4502
Epoch 38/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 415us/step - accuracy: 0.8043 - loss: 0.4084 - val_accuracy: 0.7922 - val_loss: 0.4509
Epoch 39/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 415us/step - accuracy: 0.8091 - loss: 0.4004 - val_accuracy: 0.7917 - val_loss: 0.4501
Epoch 40/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 415us/step - accuracy: 0.8041 - loss: 0.4095 - val_accuracy: 0.7937 - val_loss: 0.4537
Epoch 41/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 415us/step - accuracy: 0.8047 - loss: 0.4041 - val_accuracy: 0.7914 - val_loss: 0.4514
Epoch 42/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 420us/step - accuracy: 0.8110 - loss: 0.3981 - val_accuracy: 0.7914 - val_loss: 0.4523
Epoch 43/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 416us/step - accuracy: 0.8136 - loss: 0.3992 - val_accuracy: 0.7898 - val_loss: 0.4564
Epoch 44/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 418us/step - accuracy: 0.8037 - loss: 0.4064 - val_accuracy: 0.7906 - val_loss: 0.4538
Epoch 45/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 416us/step - accuracy: 0.8054 - loss: 0.4048 - val_accuracy: 0.7909 - val_loss: 0.4540
Epoch 46/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 459us/step - accuracy: 0.8093 - loss: 0.3997 - val_accuracy: 0.7917 - val_loss: 0.4576
Epoch 47/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 421us/step - accuracy: 0.8107 - loss: 0.4024 - val_accuracy: 0.7898 - val_loss: 0.4534
Epoch 48/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 419us/step - accuracy: 0.8081 - loss: 0.4016 - val_accuracy: 0.7914 - val_loss: 0.4520
Epoch 49/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 417us/step - accuracy: 0.8070 - loss: 0.4049 - val_accuracy: 0.7927 - val_loss: 0.4570
Epoch 50/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 419us/step - accuracy: 0.8085 - loss: 0.4029 - val_accuracy: 0.7904 - val_loss: 0.4527
Epoch 51/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 418us/step - accuracy: 0.8013 - loss: 0.4104 - val_accuracy: 0.7922 - val_loss: 0.4583
Epoch 52/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 423us/step - accuracy: 0.8086 - loss: 0.4031 - val_accuracy: 0.7906 - val_loss: 0.4558
Epoch 53/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 420us/step - accuracy: 0.8111 - loss: 0.4022 - val_accuracy: 0.7935 - val_loss: 0.4605
Epoch 54/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 465us/step - accuracy: 0.8075 - loss: 0.4031 - val_accuracy: 0.7932 - val_loss: 0.4639
Epoch 55/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 419us/step - accuracy: 0.8097 - loss: 0.3987 - val_accuracy: 0.7919 - val_loss: 0.4607
Epoch 56/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 418us/step - accuracy: 0.8101 - loss: 0.4003 - val_accuracy: 0.7906 - val_loss: 0.4564
Epoch 57/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 420us/step - accuracy: 0.8119 - loss: 0.3985 - val_accuracy: 0.7932 - val_loss: 0.4567
Epoch 58/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 419us/step - accuracy: 0.8088 - loss: 0.3988 - val_accuracy: 0.7927 - val_loss: 0.4605
Epoch 59/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 477us/step - accuracy: 0.8079 - loss: 0.4012 - val_accuracy: 0.7906 - val_loss: 0.4640
Epoch 60/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 425us/step - accuracy: 0.8093 - loss: 0.4012 - val_accuracy: 0.7942 - val_loss: 0.4588
Epoch 61/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 420us/step - accuracy: 0.8082 - loss: 0.4006 - val_accuracy: 0.7953 - val_loss: 0.4565
Epoch 62/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 421us/step - accuracy: 0.8068 - loss: 0.4028 - val_accuracy: 0.7922 - val_loss: 0.4640
Epoch 63/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 420us/step - accuracy: 0.8075 - loss: 0.3972 - val_accuracy: 0.7904 - val_loss: 0.4606
Epoch 64/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.8098 - loss: 0.4012 - val_accuracy: 0.7924 - val_loss: 0.4645
Epoch 65/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 425us/step - accuracy: 0.8069 - loss: 0.3997 - val_accuracy: 0.7937 - val_loss: 0.4581
Epoch 66/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 462us/step - accuracy: 0.8073 - loss: 0.4002 - val_accuracy: 0.7896 - val_loss: 0.4598
Epoch 67/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 423us/step - accuracy: 0.8082 - loss: 0.3993 - val_accuracy: 0.7945 - val_loss: 0.4642
Epoch 68/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 420us/step - accuracy: 0.8037 - loss: 0.4060 - val_accuracy: 0.7932 - val_loss: 0.4666
Epoch 69/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 422us/step - accuracy: 0.8087 - loss: 0.3994 - val_accuracy: 0.7901 - val_loss: 0.4704
Epoch 70/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 422us/step - accuracy: 0.8093 - loss: 0.3990 - val_accuracy: 0.7932 - val_loss: 0.4659
Epoch 71/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.8029 - loss: 0.4042 - val_accuracy: 0.7948 - val_loss: 0.4652
Epoch 72/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 423us/step - accuracy: 0.8080 - loss: 0.4033 - val_accuracy: 0.7935 - val_loss: 0.4662
Epoch 73/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 468us/step - accuracy: 0.8071 - loss: 0.4000 - val_accuracy: 0.7932 - val_loss: 0.4632
Epoch 74/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 421us/step - accuracy: 0.8104 - loss: 0.3981 - val_accuracy: 0.7919 - val_loss: 0.4660
Epoch 75/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 422us/step - accuracy: 0.8096 - loss: 0.3985 - val_accuracy: 0.7940 - val_loss: 0.4594
Epoch 76/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 421us/step - accuracy: 0.8080 - loss: 0.3998 - val_accuracy: 0.7924 - val_loss: 0.4676
Epoch 77/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 424us/step - accuracy: 0.8107 - loss: 0.3975 - val_accuracy: 0.7927 - val_loss: 0.4671
Epoch 78/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 421us/step - accuracy: 0.8110 - loss: 0.3955 - val_accuracy: 0.7937 - val_loss: 0.4684
Epoch 79/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 467us/step - accuracy: 0.8078 - loss: 0.3957 - val_accuracy: 0.7911 - val_loss: 0.4702
Epoch 80/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 425us/step - accuracy: 0.8108 - loss: 0.3989 - val_accuracy: 0.7906 - val_loss: 0.4697
Epoch 81/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 424us/step - accuracy: 0.8061 - loss: 0.4002 - val_accuracy: 0.7904 - val_loss: 0.4641
Epoch 82/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 424us/step - accuracy: 0.8071 - loss: 0.4015 - val_accuracy: 0.7917 - val_loss: 0.4662
Epoch 83/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.8120 - loss: 0.3961 - val_accuracy: 0.7930 - val_loss: 0.4673
Epoch 84/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 470us/step - accuracy: 0.8056 - loss: 0.4049 - val_accuracy: 0.7911 - val_loss: 0.4718
Epoch 85/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 425us/step - accuracy: 0.8084 - loss: 0.3998 - val_accuracy: 0.7896 - val_loss: 0.4725
Epoch 86/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 426us/step - accuracy: 0.8117 - loss: 0.3962 - val_accuracy: 0.7927 - val_loss: 0.4711
Epoch 87/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.8088 - loss: 0.3999 - val_accuracy: 0.7906 - val_loss: 0.4676
Epoch 88/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.8081 - loss: 0.4023 - val_accuracy: 0.7924 - val_loss: 0.4761
Epoch 89/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 463us/step - accuracy: 0.8070 - loss: 0.4019 - val_accuracy: 0.7924 - val_loss: 0.4709
Epoch 90/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.8133 - loss: 0.3921 - val_accuracy: 0.7914 - val_loss: 0.4739
Epoch 91/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 426us/step - accuracy: 0.8094 - loss: 0.3975 - val_accuracy: 0.7904 - val_loss: 0.4748
Epoch 92/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.8078 - loss: 0.3991 - val_accuracy: 0.7885 - val_loss: 0.4722
Epoch 93/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - accuracy: 0.8133 - loss: 0.3937 - val_accuracy: 0.7914 - val_loss: 0.4740
Epoch 94/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 464us/step - accuracy: 0.8100 - loss: 0.3943 - val_accuracy: 0.7896 - val_loss: 0.4679
Epoch 95/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.8077 - loss: 0.3968 - val_accuracy: 0.7914 - val_loss: 0.4722
Epoch 96/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 425us/step - accuracy: 0.8080 - loss: 0.4010 - val_accuracy: 0.7898 - val_loss: 0.4771
Epoch 97/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.8103 - loss: 0.3959 - val_accuracy: 0.7904 - val_loss: 0.4723
Epoch 98/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.8030 - loss: 0.4049 - val_accuracy: 0.7911 - val_loss: 0.4776
Epoch 99/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 471us/step - accuracy: 0.8098 - loss: 0.3941 - val_accuracy: 0.7911 - val_loss: 0.4729
Epoch 100/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.8144 - loss: 0.3903 - val_accuracy: 0.7924 - val_loss: 0.4733

In [32]:
# Evaluate the model using the test data
model_loss, model_accuracy = optimized_nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - 298us/step - accuracy: 0.7873 - loss: 0.4756
Loss: 0.4755868911743164, Accuracy: 0.7872886061668396

In [33]:
# Export our model to HDF5 file
optimized_nn_model.save("AlphabetSoupCharity__Optimization_Model_V3.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.