## Preprocessing

In [26]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf

# Import pandas and read the charity_data.csv from the provided cloud URL.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [27]:
# Drop the non-beneficial ID columns, 'EIN' 
application_df = application_df.drop(["EIN"],axis=1)

application_df.head()

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [28]:
# Determine the number of unique values in each column.
application_df.nunique()

NAME                      19568
APPLICATION_TYPE             17
AFFILIATION                   6
CLASSIFICATION               71
USE_CASE                      5
ORGANIZATION                  4
STATUS                        2
INCOME_AMT                    9
SPECIAL_CONSIDERATIONS        2
ASK_AMT                    8747
IS_SUCCESSFUL                 2
dtype: int64

In [29]:
# Look at NAME value counts for grouping
name_value_counts = application_df["NAME"].value_counts()

# Check name_value_counts greater than five. 
name_value_counts[name_value_counts>5]

NAME
PARENT BOOSTER USA INC                             1260
TOPS CLUB INC                                       765
UNITED STATES BOWLING CONGRESS INC                  700
WASHINGTON STATE UNIVERSITY                         492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC     408
                                                   ...
OLD OAK CLIFF CONSERVATION LEAGUE INC                 6
AMERICAN NEPHROLOGY NURSES ASSOCIATION                6
HUMBLE ISD EDUCATIONAL SUPPORT GROUPS INC             6
PROFESSIONAL LOADMASTER ASSOCIATION                   6
CBMC INC                                              6
Name: count, Length: 354, dtype: int64

In [30]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
name_groups_to_replace = list(name_value_counts[name_value_counts<=5].index)

# Replace in dataframe
for app in name_groups_to_replace:
    application_df["NAME"] = application_df["NAME"].replace(app,"Other")

# Check to make sure replacement was successful
application_df["NAME"].value_counts()

NAME
Other                                           20043
PARENT BOOSTER USA INC                           1260
TOPS CLUB INC                                     765
UNITED STATES BOWLING CONGRESS INC                700
WASHINGTON STATE UNIVERSITY                       492
                                                ...
HABITAT FOR HUMANITY INTERNATIONAL                  6
DAMAGE PREVENTION COUNCIL OF TEXAS                  6
FLEET RESERVE ASSOCIATION                           6
HUGH OBRIAN YOUTH LEADERSHIP                        6
INTERNATIONAL CONGRESS OF CHURCHES MINISTERS        6
Name: count, Length: 355, dtype: int64

In [31]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_value_counts = application_df["APPLICATION_TYPE"].value_counts()
application_value_counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [32]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(application_value_counts[application_value_counts < 1000].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
Other     2266
T4        1542
T6        1216
T5        1173
T19       1065
Name: count, dtype: int64

In [33]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_value_counts = application_df["CLASSIFICATION"].value_counts()
classification_value_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [34]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification_value_counts[classification_value_counts < 1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [35]:
# Convert categorical data to numeric with `pd.get_dummies`
numeric_df = pd.get_dummies(application_df)
numeric_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_AACE INTERNATIONAL,NAME_ACE MENTOR PROGRAM OF AMERICA INC,NAME_AFRICAN-AMERICAN POSTAL LEAGUE UNITED FOR SUCCESS A-PLUS,NAME_AIR FORCE ASSOCIATION,NAME_ALABAMA FEDERATION OF WOMENS CLUBS,NAME_ALABAMA TREASURE FOREST ASSOCIATION,NAME_ALBANY STATE UNIVERSITY NATIONAL ALUMNI ASSOCIATION,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [36]:
# Convert to a consistent numeric type
numeric_df = numeric_df.astype('int')

In [37]:
# Confirm all columns are numeric
print(numeric_df.dtypes)

STATUS                                    int64
ASK_AMT                                   int64
IS_SUCCESSFUL                             int64
NAME_AACE INTERNATIONAL                   int64
NAME_ACE MENTOR PROGRAM OF AMERICA INC    int64
                                          ...
INCOME_AMT_25000-99999                    int64
INCOME_AMT_50M+                           int64
INCOME_AMT_5M-10M                         int64
SPECIAL_CONSIDERATIONS_N                  int64
SPECIAL_CONSIDERATIONS_Y                  int64
Length: 396, dtype: object

In [38]:
# Split our preprocessed data into our features and target arrays
X = numeric_df.drop(["IS_SUCCESSFUL"], axis=1)
y = numeric_df["IS_SUCCESSFUL"]

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=48)

In [39]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [40]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 80
hidden_nodes_layer2 = 30

optimized_nn_model = tf.keras.models.Sequential()

# First hidden layer
optimized_nn_model.add(tf.keras.layers.Dense(units=hidden_nodes_layer1,
                                   input_dim=number_input_features, activation="relu"))

# Second hidden layer
optimized_nn_model.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="sigmoid"))

# Output layer
optimized_nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
optimized_nn_model.summary()

/opt/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 80)             │        31,680 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 30)             │         2,430 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 34,141 (133.36 KB)

 Trainable params: 34,141 (133.36 KB)

 Non-trainable params: 0 (0.00 B)

In [42]:
# Compile the model
optimized_nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [44]:
# Train the model
fit_model = optimized_nn_model.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 388us/step - accuracy: 0.7474 - loss: 0.5205
Epoch 2/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 378us/step - accuracy: 0.7917 - loss: 0.4341
Epoch 3/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 406us/step - accuracy: 0.7991 - loss: 0.4265
Epoch 4/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 382us/step - accuracy: 0.8009 - loss: 0.4206
Epoch 5/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 378us/step - accuracy: 0.7922 - loss: 0.4271
Epoch 6/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 378us/step - accuracy: 0.7987 - loss: 0.4212
Epoch 7/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 379us/step - accuracy: 0.7992 - loss: 0.4210
Epoch 8/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 378us/step - accuracy: 0.7944 - loss: 0.4250
Epoch 9/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 378us/step - accuracy: 0.7930 - loss: 0.4241
Epoch 10/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 383us/step - accuracy: 0.7962 - loss: 0.4201
Epoch 11/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 388us/step - accuracy: 0.8001 - loss: 0.4155
Epoch 12/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 421us/step - accuracy: 0.8003 - loss: 0.4167
Epoch 13/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 385us/step - accuracy: 0.8014 - loss: 0.4158
Epoch 14/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 379us/step - accuracy: 0.8009 - loss: 0.4134
Epoch 15/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 378us/step - accuracy: 0.8021 - loss: 0.4198
Epoch 16/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 379us/step - accuracy: 0.8003 - loss: 0.4150
Epoch 17/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 378us/step - accuracy: 0.7983 - loss: 0.4167
Epoch 18/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 378us/step - accuracy: 0.8024 - loss: 0.4121
Epoch 19/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 379us/step - accuracy: 0.7996 - loss: 0.4171
Epoch 20/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 379us/step - accuracy: 0.8014 - loss: 0.4161
Epoch 21/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 383us/step - accuracy: 0.8047 - loss: 0.4087
Epoch 22/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 383us/step - accuracy: 0.7997 - loss: 0.4153
Epoch 23/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 386us/step - accuracy: 0.8047 - loss: 0.4132
Epoch 24/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 424us/step - accuracy: 0.8010 - loss: 0.4138
Epoch 25/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 382us/step - accuracy: 0.8054 - loss: 0.4121
Epoch 26/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 385us/step - accuracy: 0.8032 - loss: 0.4103
Epoch 27/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 385us/step - accuracy: 0.8001 - loss: 0.4150
Epoch 28/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 387us/step - accuracy: 0.8065 - loss: 0.4073
Epoch 29/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 386us/step - accuracy: 0.8034 - loss: 0.4145
Epoch 30/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 387us/step - accuracy: 0.8027 - loss: 0.4119
Epoch 31/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 388us/step - accuracy: 0.8054 - loss: 0.4087
Epoch 32/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 388us/step - accuracy: 0.8037 - loss: 0.4136
Epoch 33/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 385us/step - accuracy: 0.8000 - loss: 0.4126
Epoch 34/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 419us/step - accuracy: 0.8045 - loss: 0.4094
Epoch 35/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 387us/step - accuracy: 0.8093 - loss: 0.4057
Epoch 36/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 387us/step - accuracy: 0.8052 - loss: 0.4084
Epoch 37/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 390us/step - accuracy: 0.8028 - loss: 0.4107
Epoch 38/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 391us/step - accuracy: 0.8083 - loss: 0.4049
Epoch 39/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 388us/step - accuracy: 0.8031 - loss: 0.4121
Epoch 40/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 388us/step - accuracy: 0.8024 - loss: 0.4125
Epoch 41/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 390us/step - accuracy: 0.8057 - loss: 0.4087
Epoch 42/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 389us/step - accuracy: 0.8018 - loss: 0.4150
Epoch 43/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 391us/step - accuracy: 0.8084 - loss: 0.4055
Epoch 44/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 392us/step - accuracy: 0.8053 - loss: 0.4096
Epoch 45/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 390us/step - accuracy: 0.8042 - loss: 0.4092
Epoch 46/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 391us/step - accuracy: 0.8082 - loss: 0.4035
Epoch 47/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 426us/step - accuracy: 0.8036 - loss: 0.4063
Epoch 48/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 391us/step - accuracy: 0.8100 - loss: 0.4048
Epoch 49/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 391us/step - accuracy: 0.8109 - loss: 0.4023
Epoch 50/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 392us/step - accuracy: 0.8051 - loss: 0.4067
Epoch 51/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 394us/step - accuracy: 0.8088 - loss: 0.4038
Epoch 52/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 401us/step - accuracy: 0.8047 - loss: 0.4058
Epoch 53/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 394us/step - accuracy: 0.8076 - loss: 0.4066
Epoch 54/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 395us/step - accuracy: 0.8083 - loss: 0.4019
Epoch 55/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 391us/step - accuracy: 0.8066 - loss: 0.4035
Epoch 56/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 392us/step - accuracy: 0.8024 - loss: 0.4073
Epoch 57/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 391us/step - accuracy: 0.8133 - loss: 0.3997
Epoch 58/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 391us/step - accuracy: 0.8082 - loss: 0.4019
Epoch 59/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 392us/step - accuracy: 0.8068 - loss: 0.4037
Epoch 60/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 393us/step - accuracy: 0.8064 - loss: 0.4080
Epoch 61/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 393us/step - accuracy: 0.8094 - loss: 0.4011
Epoch 62/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 393us/step - accuracy: 0.8093 - loss: 0.4056
Epoch 63/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 392us/step - accuracy: 0.8047 - loss: 0.4109
Epoch 64/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 391us/step - accuracy: 0.8023 - loss: 0.4104
Epoch 65/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 391us/step - accuracy: 0.8080 - loss: 0.4056
Epoch 66/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 391us/step - accuracy: 0.8095 - loss: 0.4025
Epoch 67/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 393us/step - accuracy: 0.8065 - loss: 0.4065
Epoch 68/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 392us/step - accuracy: 0.8062 - loss: 0.4055
Epoch 69/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 396us/step - accuracy: 0.8081 - loss: 0.4046
Epoch 70/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 392us/step - accuracy: 0.8119 - loss: 0.3991
Epoch 71/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 391us/step - accuracy: 0.8086 - loss: 0.4031
Epoch 72/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 393us/step - accuracy: 0.8081 - loss: 0.4024
Epoch 73/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.8077 - loss: 0.4014
Epoch 74/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 393us/step - accuracy: 0.8076 - loss: 0.3997
Epoch 75/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 392us/step - accuracy: 0.8102 - loss: 0.4012
Epoch 76/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 392us/step - accuracy: 0.8121 - loss: 0.3993
Epoch 77/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 394us/step - accuracy: 0.8061 - loss: 0.4056
Epoch 78/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 394us/step - accuracy: 0.8108 - loss: 0.4042
Epoch 79/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 393us/step - accuracy: 0.8087 - loss: 0.4009
Epoch 80/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 394us/step - accuracy: 0.8131 - loss: 0.3981
Epoch 81/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 392us/step - accuracy: 0.8055 - loss: 0.4085
Epoch 82/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 392us/step - accuracy: 0.8062 - loss: 0.4060
Epoch 83/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 393us/step - accuracy: 0.8058 - loss: 0.4048
Epoch 84/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 392us/step - accuracy: 0.8081 - loss: 0.4011
Epoch 85/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 391us/step - accuracy: 0.8030 - loss: 0.4054
Epoch 86/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 393us/step - accuracy: 0.8059 - loss: 0.4030
Epoch 87/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 392us/step - accuracy: 0.8095 - loss: 0.4026
Epoch 88/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 392us/step - accuracy: 0.8086 - loss: 0.3989
Epoch 89/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 392us/step - accuracy: 0.8081 - loss: 0.4004
Epoch 90/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 392us/step - accuracy: 0.8116 - loss: 0.3985
Epoch 91/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 393us/step - accuracy: 0.8107 - loss: 0.3976
Epoch 92/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.8063 - loss: 0.4057
Epoch 93/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 393us/step - accuracy: 0.8094 - loss: 0.4017
Epoch 94/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 392us/step - accuracy: 0.8094 - loss: 0.4006
Epoch 95/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.8064 - loss: 0.4034
Epoch 96/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 391us/step - accuracy: 0.8105 - loss: 0.4000
Epoch 97/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 393us/step - accuracy: 0.8082 - loss: 0.4026
Epoch 98/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 394us/step - accuracy: 0.8114 - loss: 0.4005
Epoch 99/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 393us/step - accuracy: 0.8064 - loss: 0.4018
Epoch 100/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 394us/step - accuracy: 0.8086 - loss: 0.4056

In [46]:
# Evaluate the model using the test data
model_loss, model_accuracy = optimized_nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - 335us/step - accuracy: 0.7900 - loss: 0.4443
Loss: 0.4442997872829437, Accuracy: 0.789970874786377

In [48]:
# Export our model to HDF5 file
optimized_nn_model.save("AlphabetSoupCharity__Optimization_Model_V2.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.